export default {
  test: "التست",
  "Exel export": "خروجی اکسل",
  "Number of output items": "تعداد آیتم خروجی",
  "Desired fields": "فیلد های مورد نظر",
  Print: "پرینت",
  "Get Data": "دریافت اطلاعات",
  Download: "دانلود",
  "Delete selected items": "حذف موارد انتخابی",
  Upload: "آپلود",
  "Uploaded successfully": "با موفقیت آپلود شد",
  "There was a problem sending the file": "مشکلی در ارسال فایل رخ داده است",
  Uploaded: "آپلود شده",
  Add: "اضافه کردن",
  Delete: "حذف",
  "Are you sure you want to delete it?": "آیا از حذف مطمئن هستید؟",
  Cancel: "لغو",
  Show: "نمایش",
  Edit: "ویرایش",
  Reset: "ریست",
  Search: "جستوجو",
  "no data available": "اطلاعاتی موجود نیست",
  "See details": "نمایش جزئیات",
  Fields: "فیلدها",
  validations: {
    required: "وارد کردن این مورد الزامی است",
    maxChar: "حداکثر کاراکتر مجاز {number} می باشد",
    minChar: "حداقل کاراکتر مجاز {number} می باشد",
    email: "ایمیل وارد شده صحیح نمی باشد",
    charBetween: "کاراکتر وارد شده باید بین {min} و {max} باشد",
    digits: "نعداد اعداد وارد شده صحیح نمی باشد",
    phone: "تلفن وارد شده معتبر نمی باشد",
  },
};
