export default {
  test: "اختبار",
  Actions: "أجراءات",
  "Exel export": "تصدير Excel",
  "Number of output items": "عدد عناصر الإخراج",
  "Desired fields": "الحقول المطلوبة",
  Print: "مطبعة",
  "Get Data": "احصل على البيانات",
  Download: "تحميل",
  "Delete selected items": "حذف العناصر المحددة",
  Upload: "تحميل",
  "Uploaded successfully": "تم الرفع بنجاح",
  "There was a problem sending the file": "كانت هناك مشكلة في إرسال الملف",
  Uploaded: "تم الرفع",
  Add: "يضيف",
  Delete: "حذف",
  "Are you sure you want to delete it?": "هل أنت متأكد أنك تريد حذف ذلك؟",
  Cancel: "يلغي:",
  Show: "يعرض",
  Edit: "يحرر",
  Reset: "إعادة ضبط",
  Search: "يبحث",
  "no data available": "لا تتوافر بيانات",
  "See details": "انظر التفاصيل",
  Fields: "مجالات",
  validations: {
    required: "هذا العنصر مطلوب",
    maxChar: "الحد الأقصى لعدد الأحرف هو {number}",
    minChar: "الحد الأدنى لعدد الأحرف هو {number}",
    email: "البريد الإلكتروني غير صالح",
    charBetween: "يجب أن يكون عدد الأحرف بين {min} و {max}",
    digits: "الرقم غير صالح",
    phone: "الهاتف غير صالح",
  },
  "Search text ...": "نص البحث ...",
};
