export default {
  test: "test",
  "Exel export": "Exel export",
  "Number of output items": "Number of output items",
  "Desired fields": "Desired fields",
  Print: "Print",
  "Get Data": "Get Data",
  Download: "Download",
  "Delete selected items": "Delete selected items",
  Upload: "Upload",
  "Uploaded successfully": "Uploaded successfully",
  "There was a problem sending the file":
    "There was a problem sending the file",
  Uploaded: "Uploaded",
  Add: "Add",
  Delete: "Delete",
  "Are you sure you want to delete it?": "Are you sure you want to delete it?",
  Cancel: "Cancel:",
  Show: "Show",
  Edit: "Edit",
  Reset: "Reset",
  Search: "Search",
  "no data available": "no data available",
  "See details": "See details",
  Fields: "Fields",
  validations: {
    required: "This item is required",
    maxChar: "Maximum number of characters is {number}",
    minChar: "Minimum number of characters is {number}",
    email: "Email is not valid",
    charBetween: "Number of characters must be between {min} and {max}",
    digits: "Number is not valid",
    phone: "Phone is not valid",
  },
};
