export default [
  {
    title: "تصویر",
    field: "img",
    type: "cropper",
    isHeader: true,
    uploadPath: "http://localhost:8000/api/uplaod-file",
    col: { md: 12 },
    group: "اطلاعات محصول",
  },
  {
    title: "نام محصول",
    field: "name",
    type: "text",
    isHeader: true,
    col: { md: 12 },
    group: "اطلاعات محصول",
  },
  {
    title: "منو",
    field: "menu",
    sendKey: "menu_id",
    type: "select",
    rel: {
      model: "Menu",
    },
    props: {
      "item-text": "title",
      "item-value": "id",
    },
    isHeader: true,
    col: { md: 6 },
    group: "اطلاعات محصول",
  },
  {
    title: "قیمت",
    field: "price",
    type: "text",
    props: {
      type: "number",
    },
    isHeader: true,
    col: { md: 6 },
    group: "اطلاعات محصول",
  },
  {
    title: "قیمت بیرون بر",
    field: "delivery_price",
    type: "text",
    props: {
      type: "number",
    },
    isHeader: true,
    col: { md: 6 },
    group: "اطلاعات محصول",
  },
  {
    title: "رتبه",
    field: "rate",
    type: "text",
    props: {
      type: "number",
    },
    isHeader: true,
    col: { md: 6 },
    group: "اطلاعات محصول",
  },
  {
    title: "آلرژی",
    field: "allergy",
    type: "textarea",
    isHeader: true,
    col: { md: 12 },
    group: "اطلاعات محصول",
  },
  {
    title: "توضیحات",
    field: "description",
    type: "textarea",
    isHeader: true,
    group: "اطلاعات محصول",
  },
  {
    title: "نمایش",
    field: "show",
    type: "switcher",
    isHeader: true,
    default: true,
    col: { md: 6 },
    group: "اطلاعات محصول",
  },
  {
    title: "تعریف به عنوان آپشن",
    field: "is_option",
    type: "switcher",
    default: false,
    isHeader: true,
    col: { md: 6 },
    group: "اطلاعات محصول",
  },
];
